### ISSUE TITLE
Error in prometheus metrics

### ISSUE THREAD

**Issue by batazor** [onzack/grafana-dashboards#3]
The queries are not correct? The original queries do not display the information, but if you correct them, the data starts to be displayed

**From:**
```
container_memory_working_set_bytes:sum{namespace=~"$namespace"}
```

**To:**
```
sum(container_memory_working_set_bytes{namespace="$namespace"})
```

Or do additional settings need to be made?

**Comment by ashseqera** [comment]
facing the same issue . Have been able to resolve this

**Comment by batazor** [comment]
As a result, I do not use this dashboard set, it does not seem that it is supposed to be actively supported

**Comment by ashseqera** [comment]
Appreciate your response. Thanks

**Comment by strowi** [comment]
First of all Thank you for these dashboards ;)

It seems i am running into a similar issue:


```
# Query:

# query: instance:kube_node_role
topk by (node) (1,kube_node_role * on(node) group_left(instance) label_replace(node_uname_info, "node", "$1", "nodename", "(.*)"))

# Result:
instance:kube_node_role{container="kube-state-metrics", endpoint="http", instance="10.0.0.101:9796", job="kube-state-metrics", namespace="cattle-monitoring-system", node="xyz-agent-medium-fsn1-sao", pod="rancher-monitoring-kube-state-metrics-6b8f587c5c-h9hn6", role="worker", service="rancher-monitoring-kube-state-metrics"}1
instance:kube_node_role{container="kube-state-metrics", endpoint="http", instance="10.0.0.102:9796", job="kube-state-metrics", namespace="cattle-monitoring-system", node="xyz-agent-medium-fsn1-dsg", pod="rancher-monitoring-kube-state-metrics-6b8f587c5c-h9hn6", role="worker", service="rancher-monitoring-kube-state-metrics"}1
instance:kube_node_role{container="kube-state-metrics", endpoint="http", instance="10.1.0.101:9796", job="kube-state-metrics", namespace="cattle-monitoring-system", node="xyz-agent-medium-nbg1-rjq", pod="rancher-monitoring-kube-state-metrics-6b8f587c5c-h9hn6", role="worker", service="rancher-monitoring-kube-state-metrics"}1
instance:kube_node_role{container="kube-state-metrics", endpoint="http", instance="10.255.0.101:9796", job="kube-state-metrics", namespace="cattle-monitoring-system", node="xyz-control-plane-fsn1-ket", pod="rancher-monitoring-kube-state-metrics-6b8f587c5c-h9hn6", role="control-plane", service="rancher-monitoring-kube-state-metrics"} 1
```

But then:

```yaml
# query: container_cpu_usage_seconds_total:sum_rate5m
sum by (container,pod,namespace,node,role) (
  rate(container_cpu_usage_seconds_total{container!="", container!="POD"}[5m]) * on(pod, namespace) group_left() (kube_pod_status_phase{phase="Running"}==1) * on(node) group_left(role) instance:kube_node_role
)

# Result:
Empty
```

From my pov it looks like there is no matching on `node` because `container_cpu_usage_seconds_total` simply doesn't contain `node`.

**Comment by lucatr** [comment]
Hi @strowi 

We are running the Kubernetes Server version v1.27.3. The included cAdvisor version v0.47.2 provides the `node` label in the `container_cpu_usage_seconds_total` metric.

Could you check what cAdvisor version you're running? Note, there was an issues with retrieving metrics from cAdvisor from Docker containers in k8s version v1.24 [1][2]. The workaround included deploying a standalone cAdvisor instance.

[1] https://www.suse.com/support/kb/doc/?id=000020951
[2] https://github.com/rancher/rancher/issues/38934#issuecomment-1294585708

**Comment by strowi** [comment]
Hi @lucatr ,

we are running K3s - v1.27.3 with containerd. I thought i remembered, that we had similar problem previously (at another company), so i checked and applied the old rules quickly. ;)
Since some clusters are running on IoT-devices, it might become a resource-problem to deploy an extra cadvisor.

Sadly it doesn't really report the version, but it might not be the current one.

```
cadvisor_version_info{cadvisorRevision="",cadvisorVersion="",dockerVersion="",kernelVersion="5.15.0-69-generic",osVersion="Ubuntu 22.04.2 LTS"} 1
```

All the other labels are there (including the `image` which the rancher-issue talks about), just not the `node`-label which is being joined on.

```
container_cpu_usage_seconds_total{component="k3s-server", container="alertmanager", cpu="total", endpoint="metrics", id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-poda1e74313_04ee_4a4a_ba07_f48c84bd34c1.slice/cri-containerd-3531d521a19aad55ebf4cbc2aa1c6aee2a546ee6576dda3282c8297be0709479.scope", image="docker.io/prom/alertmanager:v0.25.0", instance="x.x.x.x.:10250", job="k3s-server", metrics_path="/metrics/cadvisor", name="3531d521a19aad55ebf4cbc2aa1c6aee2a546ee6576dda3282c8297be0709479", namespace="victoriametrics", pod="vmalertmanager-0-0", service="pushprox-k3s-server-client"}
```

So i solved the problem for my end. But it still might be problematic for people not using the latest cadvisor-version, which needs that additional join on `kube_pod_info` to get the node-name over to the container.

**Comment by lucatr** [comment]
Hi @strowi 

Thank you for your feedback. I'd be interested to learn more about your setup. What Prometheus version and deployment are you using? Are you using Prometheus Operator?

I've just tested the metrics with  kube-prometheus-stack [1] deployed on k3s v1.27.3. cAdviser is included in Kubelet, version should be the latest with this k3s version.

`container_cpu_usage_seconds_total{container="alertmanager",cpu="total",endpoint="https-metrics",id="/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podad575938_e1f7_4d91_b0be_2daad4d9f187.slice/cri-containerd-60b732f42154cc696028cc72d5a5aa73f1d4a64e3de31f379b757c214b1f3878.scope",image="quay.io/prometheus/alertmanager:v0.25.0",instance="x.x.x.x:10250",job="kubelet",metrics_path="/metrics/cadvisor",name="60b732f42154cc696028cc72d5a5aa73f1d4a64e3de31f379b757c214b1f3878",namespace="monitoring",node="test-lca",pod="alertmanager-my-kube-prometheus-stack-alertmanager-0",service="my-kube-prometheus-stack-kubelet"}`

[1] https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack

**Comment by strowi** [comment]
@lucatr Yes we are using a mix of prometheus-operator (rancher-monitoring) and victoriametrics-agent (on IoT).
You just made me look at the awful relabelings and service-discovery again.. and you are totally right.
There is a `__meta_kubernetes_pod_node_name="kafka-control-plane...."` present, which gets dropped because in the rancher-monitoring-chart the relabelings are there, but get dropped because the relabeling  is commented out by default:

```yaml
    relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   targetLabel: nodename
    #   replacement: $1
    #   action: replace
```

So i guess i'll have to dig into adding those to the serviceMonitor and vmagent.

Thanks, that'll probably save me some time in the future. ;)

**Comment by lucatr** [comment]
I'll close this issue as it was initially opened due to a confusion between queries with and without Prometheus recording rules. We will further work on simplifying the deployment and making sure it works out of the box for standard use-cases. We appreciate all your inputs and feedback!
