### ISSUE TITLE
Falco Overview dashboard uid conflict

### ISSUE THREAD

**Issue by sambonbonne** [onzack/grafana-dashboards#4]
Hello,

I guessed, but I'm not sure, that you are the authors of the *Falco Overview* Grafana dashboard, which is accessible from Grafana Dashboards catalog: https://grafana.com/grafana/dashboards/17319-falco/

I use Grafana and Falco so I wanted to import your dashboard and the one from [Falco Exporter](https://grafana.com/grafana/dashboards/11914-falco-dashboard/).

I import those dashboards from Grafana's Helm chart, by using IDs for each dashboard (17319 for your's and 11914 for Falco exporter) without having to copy/paster JSON (for future updates, it will be easier).

But your dashboard and the one from Falco Exporter have the same `uid` (`FvUFlfuZz`) so it prevents me from importing both with the Grafana Helm chart.

I don't know how uids work but may it be possible to update your dashboard's `uid` so it does not conflict with Falco Exporter's one?

Thanks in advance for any help you cna give me.

**Comment by lucatr** [comment]
Hi @sambonbonne,

thank you for reporting. You are right, we are the maintainers for dashboard with gnetID 17319. It seems like both dashboards have the UID statically set to ```FvUFlfuZz```. As you've pointed out correctly, this causes the conflict in your deployment. We will update the dashboard to avoid this conflict. Unfortunately, we will not be able to get to it this week. I'll provide an update when done, next week.
In case you decide to download and import the json as a workaround, note that when no UID is provided, Grafana creates one during provisioning. So you should be fine with just removing the UID setting in the json. Drawback would be that the UID is different between each install, which means the URL of the dashboard would change as well.

**Comment by sambonbonne** [comment]
Hello @lucatr, thanks for your response and the workaround!
As you say you might be able to fix it next week, I will patiently wait.

Thanks again.

**Comment by lucatr** [comment]
Hi @sambonbonne,

we have removed the hardcoded UID from the dashboard definitions. Grafana will generate one upon installation of the dashboard. With that, the conflict you were facing should be resolved. Please make sure to use the latest revision.

btw, we've also added the Falco dashboard to this GitHub repo.

Cheers

**Comment by sambonbonne** [comment]
Hello!

Thanks for the update! I can't give it a try right now, our priorities have change, but I'm sure it will work like a charm.

I see you made another update with custom UIDs for all dashboards, with a prefix and a name depending on each dashboard so AFAIK you should be free from conflicts everywhere now :smiley: 

Cheers and thanks for your responsiveness!
