### ISSUE TITLE
Synchronize Grafana Marketplace with this Github

### ISSUE THREAD

**Issue by xmj** [onzack/grafana-dashboards#5]
Hello,

Could you please synchronize the two dashboards on Grafana Marketplace with the current versions published here?

Likewise, publishing the two versions that don't require Prometheus Rules would be nice :-)

Best
-xmj

**Comment by lucatr** [comment]
Hi @xmj,

thanks for reporting. Dashboard versions have been synchronized. Note that we also removed the hardcoded UID from the dashboard definitions as we had reports of UID collisions, which prevented installation of some dashboards. A UID will be generated by Grafana upon installation of the dashboard.

Regarding the dashboard for Kubernetes without Prometheus Rules requirement, we are evaluating which versions to maintain going forward. Especially as we have to refactor dashboards to the new format, we might ditch one or the other and focus on maintaining just one (probably the one with recording rules). For now, if you don't want to download dashboard definitions to your project, you could also import them via URL from GitHub using Grafana Operator with GrafanaDashboard CRD ([API docs](https://github.com/grafana-operator/grafana-operator/blob/master/docs/docs/api.md)). Maybe this is a feasible workaround for you.

Let us know if you have further remarks or questions.

Cheers
